/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Gateways: () => import('#controllers/gateways_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Products: () => import('#controllers/products_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Transaction: () => import('#controllers/transaction_controller'),
}
